name: Tests

on: [push, pull_request]

jobs:
  gemstash_tests:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4.7, 2.5.6, 2.6.4, jruby-9.2.9.0]
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
          wait-on: tcp://0.0.0.0:9041, tcp://0.0.0.0:9042, tcp://0.0.0.0:9043, tcp://0.0.0.0:9044
      - name: increase ulimit
        run: ulimit -n 8192
      - name: Install Dependencies
        run: gem install bundler -v 1.17.3 && bundle _1.17.3_
      - name: Run Tests
        run: bundle _1.17.3_ exec rspec --exclude-pattern "spec/integration_spec.rb"
      - name: Run Integration Tests
        run: bundle _1.17.3_ exec rspec ./spec/integration_spec.rb
    timeout-minutes: 60

